// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwcphmtsmloalfemhwly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53Y3BobXRzbWxvYWxmZW1od2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTU0NzksImV4cCI6MjA1OTE3MTQ3OX0.yNGro6854CadfX_ZSgYtAtKtw1Pm0ulQixiqOiXID_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);