
name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
        
      - name: List files before build
        run: |
          echo "Repository content before build:"
          ls -la
          
      - name: Build
        run: npm run build
        
      - name: List built files
        run: |
          echo "Build output content:"
          ls -la dist/
          
      - name: Prepare for GitHub Pages
        run: |
          # Create .nojekyll file to bypass Jekyll processing
          touch dist/.nojekyll
          echo "Created .nojekyll file"
          
          # Copy index.html to 404.html for SPA routing
          cp dist/index.html dist/404.html
          echo "Copied index.html to 404.html"
          
          # Verify the files were created correctly
          ls -la dist/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
